# Generated by Django 4.2.19 on 2025-02-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('friends', models.ManyToManyField(blank=True, related_name='friend_of', to='gestion.invite')),
            ],
        ),
        migrations.AddField(
            model_name='invite',
            name='orga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='gestion.orga'),
        ),
    ]
