# Generated by Django 4.2.19 on 2025-02-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_logemenent_invite_logement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logemenent',
            name='loges',
        ),
        migrations.RemoveField(
            model_name='orga',
            name='friends',
        ),
    ]
