# Generated by Django 4.2.19 on 2025-02-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_logemenent_loges_remove_orga_friends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logemenent',
            new_name='Logement',
        ),
    ]
