# Generated by Django 4.2.19 on 2025-02-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_rename_logemenent_logement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logement',
            name='lien',
            field=models.URLField(blank=True, null=True),
        ),
    ]
