# Generated by Django 4.2.19 on 2025-02-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_logement_lien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_type', models.CharField(choices=[('Nourriture', 'Nourriture'), ('Boisson', 'Boisson'), ('Autre', 'Autre')], max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, null=True)),
                ('prix', models.IntegerField()),
                ('quantité', models.IntegerField()),
            ],
        ),
    ]
