# Generated by Django 4.2.19 on 2025-02-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_extras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extras',
            old_name='quantité',
            new_name='quantite',
        ),
    ]
